# mecanum_robot/params/nav2_params.yaml

amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99
    resample_interval: 1
    transform_tolerance: 0.2
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""  # sẽ được rewrite từ launch file

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ["map_server", "amcl"]
