---
controller_manager:
    ros__parameters:
        update_rate: 50  # Hz

mecanum_controller:
    ros__parameters:
        type: mecanum_drive_controller/MecanumDriveController
        front_left_wheel: "front_left_wheel_joint"
        front_right_wheel: "front_right_wheel_joint"
        rear_left_wheel: "rear_left_wheel_joint"
        rear_right_wheel: "rear_right_wheel_joint"
        kinematics:
            wheels_radius: 0.03
            sum_of_robot_center_projection_on_X_Y_axis: 0.32  # lx + ly
        publish_rate: 50.0
        base_frame_id: base_link
        odom_frame_id: odom
        enable_odom_tf: true
        cmd_vel_timeout: 0.5
        velocity_rolling_window_size: 10
        ros__namespace: /mecanum_bot

joint_state_broadcaster:
    ros__parameters:
        type: joint_state_broadcaster/JointStateBroadcaster
