slam_toolbox:
  ros__parameters:
    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    max_laser_range: 10.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    map_update_interval: 5.0
    use_sim_time: false
    transform_time_offset: 0.0  # Thêm nếu cần để điều chỉnh thời gian TF