slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan_relay
    max_laser_range: 10.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    map_update_interval: 2.0
    use_sim_time: false
    transform_time_offset: 0.0 
    transform_publish_period: 0.02
    map_update_interval: 1.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    laser_max_range: 8.0
    laser_min_range: 0.2
    mode: mapping
    debug_logging: true
    message_queue_size: 1000
