ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.1

    # Odometry (encoder-based)
        #        [x_pos   , y_pos    , z_pos,
        #         roll    , pitch    , yaw,
        #         x_vel   , y_vel    , z_vel,
        #         roll_vel, pitch_vel, yaw_vel,
        #         x_accel , y_accel  , z_accel]

    odom0: /raw_odom
    odom0_config: [false, false, false,
                  false, false, true,
                  true, true, false,
                  false, false, true,
                  false, false, false]

    # IMU
    imu0: /imu/data
    imu0_config: [false, false, false,
                 true,  true,  true,
                 false, false, false,
                 false, false, false,
                 true,  true,  true]

    use_control_input: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
